"""Builds the Home Price app icon from the logo geometry.

Writes:
  app/src/main/res/drawable/ic_launcher_{foreground,background,monochrome}.xml  (Android adaptive icon)
  docs/brand/icon.svg, docs/brand/icon-monochrome.svg                         (square masters)
  docs/brand/icon-512.png                                                     (Google Play store icon)

Run from anywhere:  python docs/brand/make_icon.py
Needs:  pip install fonttools skia-pathops   and ImageMagick (`magick`) for the PNG.
"""
import shutil
import subprocess
from pathlib import Path

import pathops
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

BRAND = Path(__file__).resolve().parent
DRAWABLE = BRAND.parent.parent / "app/src/main/res/drawable"
FONT = BRAND / "fonts/NotoSerif-Bold-symbols.ttf"

DARK, LIGHT = "#201E1D", "#F3F2F2"

# Geometry is measured in pixels on the 240 px dark tile of home-price-logo.png.
# That tile maps to the 72 dp visible area of the 108 dp adaptive icon canvas.
SCALE, OFFSET = 0.3, 18.0
HOUSE = [(50, 108), (119.5, 49.5), (189.5, 108), (189.5, 193), (50, 193)]
# (symbol, colour, ink box) in drawing order; € overlaps $, ¥ overlaps €, as in the logo
SYMBOLS = [
    ("$", "#0081A7", (72, 118, 104, 182)),
    ("€", "#CC0066", (102, 107, 137, 155)),
    ("¥", "#E2B100", (133, 126, 171, 173)),
]


def dp(v):
    return round(OFFSET + v * SCALE, 2)


def fmt(v):
    return ("%.2f" % v).rstrip("0").rstrip(".")


def build_paths():
    font = TTFont(FONT)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()

    house = "M" + " L".join(f"{dp(x)},{dp(y)}" for x, y in HOUSE) + " Z"
    colored, union = [], pathops.Path()
    for ch, color, (bx0, by0, bx1, by1) in SYMBOLS:
        glyph = glyphs[cmap[ord(ch)]]
        bounds = BoundsPen(glyphs); glyph.draw(bounds); gx0, gy0, gx1, gy1 = bounds.bounds
        # Uniform scale that fits the glyph inside its box, centred; font y points up, so flip
        k = min((bx1 - bx0 + 1) * SCALE / (gx1 - gx0), (by1 - by0 + 1) * SCALE / (gy1 - gy0))
        transform = (k, 0, 0, -k,
                     dp((bx0 + bx1 + 1) / 2) - k * (gx0 + gx1) / 2,
                     dp((by0 + by1 + 1) / 2) + k * (gy0 + gy1) / 2)
        svg_pen = SVGPathPen(glyphs, ntos=fmt); glyph.draw(TransformPen(svg_pen, transform))
        colored.append((ch, color, svg_pen.getCommands()))
        outline = pathops.Path(); glyph.draw(TransformPen(outline.getPen(), transform))
        union = pathops.op(union, outline, pathops.PathOp.UNION)

    # Monochrome: the house with all symbols cut out as one shape (overlaps stay cut out)
    house_path = pathops.Path(); pen = house_path.getPen()
    pen.moveTo((dp(HOUSE[0][0]), dp(HOUSE[0][1])))
    for x, y in HOUSE[1:]:
        pen.lineTo((dp(x), dp(y)))
    pen.closePath()
    cut = pathops.op(house_path, union, pathops.PathOp.DIFFERENCE)
    mono_pen = SVGPathPen(None, ntos=fmt); cut.draw(mono_pen)
    return house, colored, mono_pen.getCommands()


def vector(body):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- Generated by docs/brand/make_icon.py; do not edit by hand -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            f"{body}</vector>\n")


def main():
    house, colored, mono = build_paths()

    (DRAWABLE / "ic_launcher_background.xml").write_text(vector(
        f'    <path android:fillColor="{DARK}" android:pathData="M0,0h108v108h-108z" />\n'))
    (DRAWABLE / "ic_launcher_foreground.xml").write_text(vector(
        f'    <path android:fillColor="{LIGHT}" android:pathData="{house}" />\n'
        + "".join(f'    <!-- {ch} -->\n    <path android:fillColor="{c}" android:pathData="{d}" />\n'
                  for ch, c, d in colored)))
    (DRAWABLE / "ic_launcher_monochrome.xml").write_text(vector(
        "    <!-- House with the symbols cut out, for themed (monochrome) icons -->\n"
        f'    <path android:fillColor="#FFFFFFFF" android:pathData="{mono}" />\n'))

    # Square masters show just the visible 72 dp area, full bleed (stores apply their own mask)
    art = f'<path fill="{LIGHT}" d="{house}"/>' + "".join(f'<path fill="{c}" d="{d}"/>' for _, c, d in colored)
    square = '<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="18 18 72 72">'
    (BRAND / "icon.svg").write_text(f'{square}<rect x="18" y="18" width="72" height="72" fill="{DARK}"/>{art}</svg>\n')
    (BRAND / "icon-monochrome.svg").write_text(f'{square}<path fill="{DARK}" d="{mono}"/></svg>\n')

    if shutil.which("magick"):
        # Google Play: 512x512, 32-bit PNG, square (Play rounds the corners itself)
        subprocess.run(["magick", "-background", "none", str(BRAND / "icon.svg"),
                        "-resize", "512x512!", f"PNG32:{BRAND / 'icon-512.png'}"], check=True)
    else:
        print("ImageMagick not found; skipped icon-512.png")
    print("Icon files written")


if __name__ == "__main__":
    main()
